# Generated by Django 2.0 on 2017-12-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_judge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
