# Generated by Django 2.0.2 on 2018-03-05 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_auto_20180304_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='magic_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(default='your mom', max_length=256)),
                ('round_submitted', models.IntegerField(default=1)),
                ('card_color', models.CharField(choices=[('U', 'Blue'), ('R', 'Red'), ('W', 'White'), ('B', 'Black'), ('G', 'Green')], max_length=5)),
                ('card_type', models.CharField(choices=[('EN', 'Enchantment'), ('AR', 'Artifact'), ('CR', 'Creature'), ('LA', 'Land'), ('PL', 'Planeswalker')], max_length=5)),
                ('converted_mana_cost', models.CharField(default='0', max_length=240)),
                ('card_text', models.CharField(default='card text', max_length=240)),
                ('flavor_text', models.CharField(default='flavor text', max_length=240)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='game.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='magic_card',
            unique_together={('player', 'card_name')},
        ),
    ]
