# Generated by Django 2.0.2 on 2018-03-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='magic_card',
            unique_together=set(),
        ),
    ]
