# Generated by Django 2.0.2 on 2018-03-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20180305_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magic_card',
            name='card_name',
        ),
    ]
