# Generated by Django 2.0.2 on 2018-03-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_magic_card_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic_card',
            name='card_name',
            field=models.CharField(default='card name', max_length=256),
        ),
    ]
