# Generated by Django 2.0.2 on 2018-03-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_magic_card_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic_card',
            name='card_name',
            field=models.CharField(default='DSBRJ', max_length=256),
        ),
    ]
