# Generated by Django 2.0.2 on 2018-03-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20180305_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic_card',
            name='card_name',
            field=models.CharField(default='GPFBQ', max_length=256),
        ),
        migrations.AlterField(
            model_name='magic_card',
            name='round_submitted',
            field=models.IntegerField(),
        ),
    ]
