# Generated by Django 2.0.2 on 2018-04-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_auto_20180401_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic_card',
            name='card_name',
            field=models.CharField(default='YIAIW', max_length=256),
        ),
    ]
