# Generated by Django 2.0.2 on 2018-04-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20180403_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic_card',
            name='card_name',
            field=models.CharField(default='DAPDQ', max_length=256),
        ),
    ]
