# Generated by Django 2.0.2 on 2018-04-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_auto_20180403_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic_card',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='magic_card',
            name='card_name',
            field=models.CharField(max_length=1000),
        ),
    ]
