# Generated by Django 2.0.2 on 2018-04-08 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_auto_20180404_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magic_card',
            name='card_name',
        ),
    ]
