# Generated by Django 2.0.2 on 2018-04-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_magic_card_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic_card',
            name='card_type',
            field=models.CharField(choices=[('Enchantment', 'Enchantment'), ('Atifact', 'Artifact'), ('Creature', 'Creature'), ('Land', 'Land'), ('Planeswalker', 'Planeswalker'), ('Sorcery', 'Sorcery'), ('Instant', 'Instant')], max_length=15),
        ),
    ]
