# Generated by Django 2.0.4 on 2018-04-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_auto_20180417_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic_card',
            name='card_text',
            field=models.TextField(default='card text', max_length=240),
        ),
        migrations.AlterField(
            model_name='magic_card',
            name='flavor_text',
            field=models.TextField(default='flavor text', max_length=240),
        ),
    ]
