# Generated by Django 2.0.4 on 2018-04-19 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_auto_20180419_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic_card',
            name='card_sub_types',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='magic_card',
            name='card_color',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red'), ('White', 'White'), ('Black', 'Black'), ('Green', 'Green')], max_length=15),
        ),
    ]
