# Generated by Django 2.0.4 on 2018-04-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_auto_20180422_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic_card',
            name='card_text',
            field=models.TextField(default='card text'),
        ),
        migrations.AlterField(
            model_name='magic_card',
            name='converted_mana_cost',
            field=models.CharField(default='i.e 2GG for 2 colorless and 2 Green', max_length=240),
        ),
        migrations.AlterField(
            model_name='magic_card',
            name='flavor_text',
            field=models.TextField(default='flavor text'),
        ),
    ]
