# Generated by Django 2.0.2 on 2018-03-05 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('judging', models.IntegerField(default=0)),
                ('number_of_players', models.IntegerField()),
                ('number_of_rounds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='magic_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(default='your mom', max_length=256)),
                ('player', models.CharField(default='rabble rabble rabble', max_length=256)),
                ('round_submitted', models.IntegerField(default=1)),
                ('card_color', models.CharField(choices=[('U', 'Blue'), ('R', 'Red'), ('W', 'White'), ('B', 'Black'), ('G', 'Green')], max_length=5)),
                ('card_type', models.CharField(choices=[('EN', 'Enchantment'), ('AR', 'Artifact'), ('CR', 'Creature'), ('LA', 'Land'), ('PL', 'Planeswalker')], max_length=5)),
                ('converted_mana_cost', models.CharField(default='0', max_length=240)),
                ('card_text', models.CharField(default='card text', max_length=240)),
                ('flavor_text', models.CharField(default='flavor text', max_length=240)),
            ],
        ),
        migrations.AddField(
            model_name='ingame',
            name='submissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.magic_card'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='game.InGame', to=settings.AUTH_USER_MODEL),
        ),
    ]
