# Generated by Django 2.0.2 on 2018-03-05 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180304_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic_card',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
